Update pom.xml to add org.apache.commons.compress dependency
Otherwise will get the following error messages -


java.lang.NoClassDefFoundError: org/apache/commons/compress/compressors/CompressorException
    at java.lang.Class.getDeclaredMethods0 (Native Method)
    at java.lang.Class.privateGetDeclaredMethods (Class.java:3402)
    at java.lang.Class.privateGetPublicMethods (Class.java:3427)
    at java.lang.Class.getMethods (Class.java:2019)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.getActionAnnotations (PackageBasedActionConfigBuilder.java:878)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildConfiguration (PackageBasedActionConfigBuilder.java:680)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildActionConfigs (PackageBasedActionConfigBuilder.java:338)
    at org.apache.struts2.convention.ClasspathPackageProvider.loadPackages (ClasspathPackageProvider.java:52)
    at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer (DefaultConfiguration.java:228)
    at com.opensymphony.xwork2.config.ConfigurationManager.reload (ConfigurationManager.java:227)
    at com.opensymphony.xwork2.config.ConfigurationManager.initialiseConfiguration (ConfigurationManager.java:84)
    at com.opensymphony.xwork2.config.ConfigurationManager.wasConfigInitialised (ConfigurationManager.java:72)
    at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration (ConfigurationManager.java:61)
    at org.apache.struts2.dispatcher.Dispatcher.getContainer (Dispatcher.java:1079)
    at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration (Dispatcher.java:537)
    at org.apache.struts2.dispatcher.Dispatcher.init (Dispatcher.java:571)
    at org.apache.struts2.dispatcher.InitOperations.initDispatcher (InitOperations.java:48)
    at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init (StrutsPrepareAndExecuteFilter.java:60)
    at org.eclipse.jetty.servlet.FilterHolder.initialize (FilterHolder.java:140)
    at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0 (ServletHandler.java:731)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:992)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining (Streams.java:734)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:762)
    at org.eclipse.jetty.servlet.ServletHandler.initialize (ServletHandler.java:755)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext (ServletContextHandler.java:379)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp (WebAppContext.java:1449)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp (JettyWebAppContext.java:328)
    at org.eclipse.jetty.webapp.WebAppContext.startContext (WebAppContext.java:1414)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart (ContextHandler.java:916)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart (ServletContextHandler.java:288)
    at org.eclipse.jetty.webapp.WebAppContext.doStart (WebAppContext.java:524)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart (JettyWebAppContext.java:397)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:117)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:117)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.server.Server.start (Server.java:423)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:110)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.server.Server.doStart (Server.java:387)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty (AbstractJettyMojo.java:449)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute (AbstractJettyMojo.java:310)
    at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute (JettyRunMojo.java:150)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.compressors.CompressorException
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass (WebAppClassLoader.java:538)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:520)
    at java.lang.Class.getDeclaredMethods0 (Native Method)
    at java.lang.Class.privateGetDeclaredMethods (Class.java:3402)
    at java.lang.Class.privateGetPublicMethods (Class.java:3427)
    at java.lang.Class.getMethods (Class.java:2019)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.getActionAnnotations (PackageBasedActionConfigBuilder.java:878)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildConfiguration (PackageBasedActionConfigBuilder.java:680)
    at org.apache.struts2.convention.PackageBasedActionConfigBuilder.buildActionConfigs (PackageBasedActionConfigBuilder.java:338)
    at org.apache.struts2.convention.ClasspathPackageProvider.loadPackages (ClasspathPackageProvider.java:52)
    at com.opensymphony.xwork2.config.impl.DefaultConfiguration.reloadContainer (DefaultConfiguration.java:228)
    at com.opensymphony.xwork2.config.ConfigurationManager.reload (ConfigurationManager.java:227)
    at com.opensymphony.xwork2.config.ConfigurationManager.initialiseConfiguration (ConfigurationManager.java:84)
    at com.opensymphony.xwork2.config.ConfigurationManager.wasConfigInitialised (ConfigurationManager.java:72)
    at com.opensymphony.xwork2.config.ConfigurationManager.getConfiguration (ConfigurationManager.java:61)
    at org.apache.struts2.dispatcher.Dispatcher.getContainer (Dispatcher.java:1079)
    at org.apache.struts2.dispatcher.Dispatcher.init_PreloadConfiguration (Dispatcher.java:537)
    at org.apache.struts2.dispatcher.Dispatcher.init (Dispatcher.java:571)
    at org.apache.struts2.dispatcher.InitOperations.initDispatcher (InitOperations.java:48)
    at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.init (StrutsPrepareAndExecuteFilter.java:60)
    at org.eclipse.jetty.servlet.FilterHolder.initialize (FilterHolder.java:140)
    at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0 (ServletHandler.java:731)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:992)
    at java.util.stream.Streams$ConcatSpliterator.forEachRemaining (Streams.java:734)
    at java.util.stream.ReferencePipeline$Head.forEach (ReferencePipeline.java:762)
    at org.eclipse.jetty.servlet.ServletHandler.initialize (ServletHandler.java:755)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext (ServletContextHandler.java:379)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp (WebAppContext.java:1449)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp (JettyWebAppContext.java:328)
    at org.eclipse.jetty.webapp.WebAppContext.startContext (WebAppContext.java:1414)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart (ContextHandler.java:916)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart (ServletContextHandler.java:288)
    at org.eclipse.jetty.webapp.WebAppContext.doStart (WebAppContext.java:524)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart (JettyWebAppContext.java:397)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:117)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:117)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:169)
    at org.eclipse.jetty.server.Server.start (Server.java:423)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:110)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:97)
    at org.eclipse.jetty.server.Server.doStart (Server.java:387)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:73)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty (AbstractJettyMojo.java:449)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute (AbstractJettyMojo.java:310)
    at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute (JettyRunMojo.java:150)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] Started ServerConnector@4e6cbdf1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[INFO] Started @5853ms
[INFO] Started Jetty Server